apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      containers:
        - name: clickhouse
          image: clickhouse/clickhouse-server:latest
          ports:
            - name: http
              containerPort: 8123
            - name: native
              containerPort: 9000
            - name: prom
              containerPort: 9363
          volumeMounts:
            - name: data
              mountPath: /var/lib/clickhouse
            - name: config
              mountPath: /etc/clickhouse-server/config.d/prometheus.xml
              subPath: prometheus.xml
            - name: config
              mountPath: /etc/clickhouse-server/users.d/users.xml
              subPath: users.xml
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: clickhouse-data
        - name: config
          configMap:
            name: clickhouse-config
