apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - clickhouse-pvc.yaml
  - clickhouse-deployment.yaml
  - clickhouse-service.yaml
  - clickhouse-init-job.yaml

configMapGenerator:
  - name: clickhouse-config
    files:
      - config/prometheus.xml
  - name: clickhouse-init-scripts
    files:
      - scripts/init.sh
      - scripts/init.sql
