apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - clickhouse-pvc.yaml
  - clickhouse-configmap.yaml
  - clickhouse-deployment.yaml
  - clickhouse-service.yaml
  - clickhouse-init-job.yaml
