apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - vector-serviceaccount.yaml
  - vector-token-secret.yaml
  - vector-rbac.yaml
  - vector-daemonset.yaml

configMapGenerator:
  - name: vector-config
    files:
      - config/vector.toml
